apiVersion: redhatcop.redhat.io/v1alpha1
kind: Policy
metadata:
  name: infra-secret-reader
spec:
  # Add fields here
  authentication: 
    path: hub
    role: vault-admin
  type: acl  
  policy: |
    # query existing mounts
    path "/infra/*" {
      capabilities = [ "list", "read"]
    }

    path "/infra/clusters/+/jwt/creds/+" {
      capabilities = [ "create", "update"]
    }    

 