apiVersion: redhatcop.redhat.io/v1alpha1
kind: KubernetesSecretEngineConfig
metadata:
  name: kube-secret-engine
  namespace: vault-admin
spec:
  authentication: 
    path: hub
    role: vault-admin
    serviceAccount:
      name: default
  path: /infra/clusters/${CLUSTER_NAME}/jwt
  kubernetesHost: https://api.${CLUSTER_BASE_DOMAIN}:6443
  jwtReference:
    secret:
      name: default-sa
    passwordKey: token