apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: kube-secret-engine
  namespace: vault-admin
spec:
  authentication: 
    path: hub
    role: vault-admin
    serviceAccount:
      name: default
  name: jwt               
  type: kubernetes
  path: /infra/clusters/${CLUSTER_NAME}
