---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault-admin
resources:
  - ./namespace.yaml
  - ./keycloak-auth-engine-mount.yaml
  - ./keycloak-auth-engine-config.yaml
  - ./keycloak-auth-engine-role.yaml
  - ./keycloak-client-secret-vault.yaml
  - ./patches-rbac.yaml
  - ./patches.yaml
  - ./default-sa-token-secret.yaml
  - ./kubernetes-secret-engine-mount.yaml
  - ./kubernetes-secret-engine-config.yaml
  - ./vault-secret-engine-role-binding.yaml
  - ./vault-secret-engine-role.yaml
  - ./infra-secret-reader-policy.yaml  
  - ./infra-secret-reader-role.yaml