apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: vault-config
spec:
  serviceAccountRef:
    name: default
  patches:
    keycloak-secret:
      targetObjectRef:
        apiVersion: v1
        kind: Secret
        namespace: vault-admin
        name: keycloak-client-secret-vault
      sourceObjectRefs:
      - apiVersion: v1
        kind: Secret
        namespace: openshift-sso
        name: keycloak-client-secret-vault        
      patchTemplate: |
        data:
          CLIENT_SECRET: {{ (index (index . 1).data "CLIENT_SECRET") }}
          CLIENT_ID: {{ (index (index . 1).data "CLIENT_ID") }}
      patchType: application/merge-patch+json
