apiVersion: redhatcop.redhat.io/v1alpha1
kind: AuthEngineMount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.vault.vaultAdminNamespace }}
  labels:
    {{- include "vault-cluster-registration.labels" . | nindent 4 }}  
spec:
  authentication: 
    {{if .Values.vault.authentication.namespace }}
    namespace: {{ .Values.vault.authentication.namespace }}
    {{end}}
    path: {{ .Values.vault.authentication.path }}
    role: {{ .Values.vault.authentication.role }}
    serviceAccount:
      name: default
  type: kubernetes