apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: aws-credentials-policy
  namespace: open-cluster-management
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: aws-credentials-policy
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
          - complianceType: musthave  
            objectDefinition:
              apiVersion: v1
              kind: Secret
              metadata:
                name: aws-secret
                namespace: crossplane-system
              type: Opaque
              data:
                creds: '{{hub (printf "[default]\naws_access_key_id = %s \naws_secret_access_key = %s" ((fromSecret "open-cluster-management" "aws-credentials" "aws_access_key_id")|base64dec) ((fromSecret "open-cluster-management" "aws-credentials" "aws_secret_access_key")|base64dec) ) | base64enc hub}}'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: aws-credentials-policy
  namespace: open-cluster-management
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: aws-credentials-policy
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: aws-credentials-policy
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: aws-credentials-policy
  namespace: open-cluster-management
spec:
  clusterSets:
    - default
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: default
  namespace: open-cluster-management
spec:
  clusterSet: default            
           