apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: keycloak
spec:
  providers:
    - name: keycloak
      keycloak:
        insecure: true
        realm: myorg
        url: <replace>
        loginRealm: master	
        prune: false
        scope: sub        
        credentialsSecret:
          kind: Secret         
          name: keycloak-creds
          namespace: openshift-group-sync-operator