apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: crossplane-secrets
spec:
  authentication: 
    path: ${CLUSTER_NAME}
    role: vault-admin
  type: kv
  path: /infra/clusters/${CLUSTER_NAME}
  options:
    version: "1"