apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: keycloak-secret-policy
  namespace: openshift-sso
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: keycloak-secret
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
          - complianceType: musthave  
            objectDefinition:
              apiVersion: v1
              kind: Secret
              metadata:
                name: oidc-secret
                namespace: openshift-config
              type: Opaque
              data:
                clientSecret: '{{hub (fromSecret "sso" (printf "keycloak-client-secret-ocp-%s" .ManagedClusterName ) "CLIENT_SECRET") hub}}'
          - complianceType: musthave  
            objectDefinition:
              apiVersion: v1
              kind: Secret
              metadata:
                name: keycloak-creds
                namespace: openshift-group-sync-operator
              type: Opaque
              data:
                username: '{{hub (fromSecret "sso" "credential-rhsso" "ADMIN_USERNAME") hub}}'
                password: '{{hub (fromSecret "sso" "credential-rhsso" "ADMIN_PASSWORD") hub}}'                
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: keycloak-secret-policy
  namespace: openshift-sso
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: keycloak-secret-policy
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: keycloak-secret-policy
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: keycloak-secret-policy
  namespace: openshift-sso
spec:
  clusterSets:
    - default
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: default
  namespace: openshift-sso
spec:
  clusterSet: default            
           