apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-app-only
rules:
- apiGroups: ["argoproj.io"] # "" indicates the core API group
  resources: ["applications"]
  verbs: ["*"]
---     
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-reader
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["list","get","watch"]  
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: tenant-gitops-rbac
spec:
  labelSelector:
    matchLabels:
      tenant-gitops: "true"      
  templates:     
  - objectTemplate: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: "{{.Name}}-argocd-reader"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: argocd-reader
      subjects:
      - kind: ServiceAccount
        name: "{{.Name}}-tenant-argocd"
        namespace: tenant-gitops
    excludedPaths:	
      - .spec.replicas	
      - .metadata	
      - .status
  - objectTemplate: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: "{{.Name}}-argocd-app-only"
        namespace: "{{.Name}}"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: argocd-app-only
      subjects:
      - kind: ServiceAccount
        name: "{{.Name}}-tenant-argocd"
        namespace: tenant-gitops
    excludedPaths:	
      - .spec.replicas	
      - .metadata	
      - .status    