apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: tenant-gitops-patches
  namespace: tenant-gitops
spec:
  serviceAccountRef:
    name: default
  patches:  
    keycloak-secret:
      targetObjectRef:
        apiVersion: v1
        kind: Secret
        namespace: tenant-gitops
        name: argocd-secret
      sourceObjectRefs:
      - apiVersion: v1
        kind: Secret
        namespace: sso
        name: keycloak-client-secret-argocd                
      patchTemplate: |
        data:
          oidc.keycloak.clientSecret: {{ (index (index . 1).data "CLIENT_SECRET") }}
      patchType: application/merge-patch+json
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: tenant-gitops-patches
spec:
  labelSelector:
    matchLabels:
      tenant-gitops: "true"      
  templates:     
  - objectTemplate: |
      apiVersion: redhatcop.redhat.io/v1alpha1
      kind: Patch
      metadata:
        name: "{{.Name}}-hub-patch"
        namespace: tenant-gitops
      spec:
        serviceAccountRef:
          name: default
        patches:
          tenant-gitops-hub:
            targetObjectRef:
              apiVersion: v1
              kind: Secret
              namespace: tenant-gitops
              name: "{{.Name}}-hub"
            sourceObjectRefs:
            - apiVersion: v1
              kind: Secret
              namespace: tenant-gitops
              name: "{{.Name}}-tenant-argocd"    
            patchTemplate: |
              data:
                config: {{"{{"}} (cat "{ \"bearerToken\": " ((index . 1).data.token | b64dec | quote) " }") | b64enc {{"}}"}}
            patchType: application/merge-patch+json            
    excludedPaths:	
      - .spec.replicas	
      - .metadata	
      - .status                           

