kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tenant-gitops-patches-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: tenant-gitops # namespace:operator
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io