apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: tenant-gitops-service-accounts
spec:
  labelSelector:
    matchLabels:
      tenant-gitops: "true"      
  templates:     
  - objectTemplate: |
      kind: ServiceAccount
      apiVersion: v1
      metadata:
        name: "{{.Name}}-tenant-argocd"
        namespace: tenant-gitops
    excludedPaths:	
      - .spec.replicas	
      - .metadata	
      - .status
  - objectTemplate: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{.Name}}-tenant-argocd"
        namespace: tenant-gitops
        annotations:
          kubernetes.io/service-account.name: {{.Name}}-tenant-argocd
      type: kubernetes.io/service-account-token
    excludedPaths:	
      - .spec.replicas	
      - .metadata	
      - .status 