apiVersion: v1
kind: Secret
metadata:
  name: prod-install-config
  namespace: 'prod'
type: Opaque
stringData:
  install-config.yaml: |-
    apiVersion: v1
    metadata:
      name: 'prod'
    baseDomain: ${PLATFORM_BASE_DOMAIN}
    controlPlane:
      architecture: amd64
      hyperthreading: Enabled
      name: master
      replicas: 3
      platform:
        aws:
          rootVolume:
            iops: 4000
            size: 100
            type: io1
          type: m5.xlarge
    compute:
    - hyperthreading: Enabled
      architecture: amd64
      name: 'worker'
      replicas: 3
      platform:
        aws:
          rootVolume:
            iops: 2000
            size: 100
            type: io1
          type: m5.xlarge
    networking:
      networkType: OVNKubernetes
      clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
      machineNetwork:
      - cidr: 10.2.0.0/16
      serviceNetwork:
      - 172.30.0.0/16
    platform:
      aws:
        region: us-east-2
    pullSecret: "" # skip, hive will inject based on it's secrets
    sshKey: |-
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCWVnOEYFaN6tp/CXn5aBgD5YZbbwJHhUYbAahoGz3IbP8YZZwyBvJvgy9CujKTaIpZHweYRwMEtvPaX65g8AQDd8t6Gqc+JVJue6HTqrawH2wvq8Qdhip9L09fK2WqtP7UbVF+fgiwm9kebajkAqtlOttcdHipeRy5TGVE2hbV1zqc6UjTo6lKzxflm2Jd5EMc4TZCleSFApBod+jgFZoke/8Q/GHWyQs7YaoE3h/JND7z6aye5HoAPQBT18y/4Amwj7h2hIcIsSJ8JAHsOZ0NB4gz1qwpkG/dYAYV1iARM/+qnZ7EJAt4DofqUAS1/0BdXK+1RL8uI0db4r8U3pTe+oFGORQHRNa+ehDoX1PdOU+o59OmjEaJpcq0YRB3NqOwfZzATUfOqcZswH0xC6WKi/UknBFPgJv6JfD0+dee/kWTmgFrzT6Ie9hRql2bA+qjSoPfWzPk+Gv1Wuf6UGdC2DpKPO+vOhVzRtog/cvwjGSJv5p2X6biRGiYy8a0bX0= rspazzol@rspazzolapiVersion: v1
#data:
  # Base64 encoding of install-config yaml
  #install-config.yaml: YXBpVmVyc2lvbjogdjEKbWV0YWRhdGE6CiAgbmFtZTogJ3Byb2QnCmJhc2VEb21haW46IGNocmkucDEub3BlbnNoaWZ0YXBwcy5jb20KY29udHJvbFBsYW5lOgogIGFyY2hpdGVjdHVyZTogYW1kNjQKICBoeXBlcnRocmVhZGluZzogRW5hYmxlZAogIG5hbWU6IG1hc3RlcgogIHJlcGxpY2FzOiAzCiAgcGxhdGZvcm06CiAgICBhd3M6CiAgICAgIHJvb3RWb2x1bWU6CiAgICAgICAgaW9wczogNDAwMAogICAgICAgIHNpemU6IDEwMAogICAgICAgIHR5cGU6IGlvMQogICAgICB0eXBlOiBtNS54bGFyZ2UKY29tcHV0ZToKLSBoeXBlcnRocmVhZGluZzogRW5hYmxlZAogIGFyY2hpdGVjdHVyZTogYW1kNjQKICBuYW1lOiAnd29ya2VyJwogIHJlcGxpY2FzOiAzCiAgcGxhdGZvcm06CiAgICBhd3M6CiAgICAgIHJvb3RWb2x1bWU6CiAgICAgICAgaW9wczogMjAwMAogICAgICAgIHNpemU6IDEwMAogICAgICAgIHR5cGU6IGlvMQogICAgICB0eXBlOiBtNS54bGFyZ2UKbmV0d29ya2luZzoKICBuZXR3b3JrVHlwZTogT1ZOS3ViZXJuZXRlcwogIGNsdXN0ZXJOZXR3b3JrOgogIC0gY2lkcjogMTAuMTI4LjAuMC8xNAogICAgaG9zdFByZWZpeDogMjMKICBtYWNoaW5lTmV0d29yazoKICAtIGNpZHI6IDEwLjAuMC4wLzE2CiAgc2VydmljZU5ldHdvcms6CiAgLSAxNzIuMzAuMC4wLzE2CnBsYXRmb3JtOgogIGF3czoKICAgIHJlZ2lvbjogdXMtZWFzdC0yCnB1bGxTZWNyZXQ6ICIiICMgc2tpcCwgaGl2ZSB3aWxsIGluamVjdCBiYXNlZCBvbiBpdCdzIHNlY3JldHMKc3NoS2V5OiB8LQogICAgc3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCZ1FDV1ZuT0VZRmFONnRwL0NYbjVhQmdENVlaYmJ3SkhoVVliQWFob0d6M0liUDhZWlp3eUJ2SnZneTlDdWpLVGFJcFpId2VZUndNRXR2UGFYNjVnOEFRRGQ4dDZHcWMrSlZKdWU2SFRxcmF3SDJ3dnE4UWRoaXA5TDA5ZksyV3F0UDdVYlZGK2ZnaXdtOWtlYmFqa0FxdGxPdHRjZEhpcGVSeTVUR1ZFMmhiVjF6cWM2VWpUbzZsS3p4ZmxtMkpkNUVNYzRUWkNsZVNGQXBCb2QramdGWm9rZS84US9HSFd5UXM3WWFvRTNoL0pORDd6NmF5ZTVIb0FQUUJUMTh5LzRBbXdqN2gyaEljSXNTSjhKQUhzT1owTkI0Z3oxcXdwa0cvZFlBWVYxaUFSTS8rcW5aN0VKQXQ0RG9mcVVBUzEvMEJkWEsrMVJMOHVJMGRiNHI4VTNwVGUrb0ZHT1JRSFJOYStlaERvWDFQZE9VK281OU9takVhSnBjcTBZUkIzTnFPd2ZaekFUVWZPcWNac3dIMHhDNldLaS9Va25CRlBnSnY2SmZEMCtkZWUva1dUbWdGcnpUNkllOWhScWwyYkErcWpTb1BmV3pQaytHdjFXdWY2VUdkQzJEcEtQTyt2T2hWelJ0b2cvY3Z3akdTSnY1cDJYNmJpUkdpWXk4YTBiWDA9IHJzcGF6em9sQHJzcGF6em9s
