kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: non-prod-patches-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: non-prod # namespace:operator
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io