apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: keycloak-provider-patches
spec:
  serviceAccountRef:
    name: default
  patches: 
    keycloak-credentials:
      targetObjectRef:
        apiVersion: v1
        kind: Secret
        namespace: crossplane-system
        name: keycloak-credentials
      sourceObjectRefs:
      - apiVersion: v1
        kind: Secret
        namespace: openshift-sso
        name: credential-rhsso         
      patchTemplate: |
        {{ $value:= dict "username" ((index (index . 1).data "ADMIN_USERNAME")|b64dec) "password" ((index (index . 1).data "ADMIN_PASSWORD")|b64dec) "url" "https://keycloak-sso.apps.${CLUSTER_BASE_DOMAIN}/auth" "client_id" "admin-cli" }}
        data:
          credentials: {{ $value | toJson | b64enc }}
      patchType: application/merge-patch+json   

