---
apiVersion: v1
kind: Service
metadata:
  name: httpd
spec:
  selector:
    app: http # match the correct app label
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: httpd
spec:
  to:
    kind: Service
    name: httpd
    weight: 100
  port:
    targetPort: http
