---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/rhsso-configuration/

patches:

  - patch: |-
      - op: replace
        path: /spec/href
        value: "https://keycloak-sso.apps.${CLUSTER_BASE_DOMAIN}"
    target:
      kind: ConsoleLink
      name: rhsso
      namespace: openshift-sso  
